const API_ENDPOINTS = {
    contentRead: (doId: string) => `/api/content/v1/read/${doId}?fields=artifactUrl`,
    academicYearsList: '/interface/v1/academicyears/list',
    coursePlannerUpload: '/prathamservice/v1/course-planner/upload',
    targetedSolutions: '/solutions/targetedSolutions?type=improvementProject&currentScopeOnly=true',
    formRead: '/interface/v1/form/read',
    accountCreate: '/interface/v1/account/create',
    userUpdate: (userId: string) => `/interface/v1/user/update/${userId}`,
    myCohorts: (userId: string | string[]) => `/interface/v1/cohort/mycohorts/${userId}`,
    accountLogin: '/interface/v1/account/login',
    authRefresh: '/interface/v1/account/auth/refresh',
    authLogout: '/interface/v1/account/auth/logout',
    userAuth: '/interface/v1/user/auth',
    resetPassword: '/interface/v1/user/reset-password',
    fieldOptionsRead: '/interface/v1/fields/options/read',
    cohortSearch: '/interface/v1/cohort/search',
    fieldOptionDelete: (type: string, option: string) => `/interface/v1/fields/options/delete/${type}?option=${option}`,
    fieldUpdate: (fieldId: string) => `/interface/v1/fields/update/${fieldId}`,
    cohortUpdate: (cohortId: string) => `/interface/v1/cohort/update/${cohortId}`,
    notificationSend: '/interface/v1/notification/send',
    tenantRead: '/interface/v1/tenant/read',
    tenantCreate: '/interface/v1/tenant/create',
    tenantUpdate: (tenantId: string) => `/interface/v1/tenant/update/${tenantId}`,
    tenantDelete: (tenantId: string) => `/interface/v1/tenant/delete/${tenantId}`,
    tenantSearch: '/interface/v1/tenant/search',
    userList: '/interface/v1/user/list',
    cohortMemberList: '/interface/v1/cohortmember/list',
    userRead: (userId: string | string[], fieldValue: boolean) => `/interface/v1/user/read/${userId}?fieldvalue=${fieldValue}`,
    suggestUsername: '/interface/v1/user/suggestUsername',
    cohortUpdateUser: (userId: string) => `/interface/v1/cohort/update/${userId}`,
    formReadWithContext: (context: string, contextType: string) => `/interface/v1/form/read?context=${context}&contextType=${contextType}`,
    cohortCreate: '/interface/v1/cohort/create',
    cohortMemberBulkCreate: '/interface/v1/cohortmember/bulkCreate',
    cohortMemberUpdate: (membershipId: string | number) => `/interface/v1/cohortmember/update/${membershipId}`,
    notificationTemplate: '/notification-templates',

  };
  
  export default API_ENDPOINTS;
  