version: '3'
services:
  learner-web-app:
    build:
      context: .
      dockerfile: Dockerfile.learner-web-app
    ports:
      - '3003:3003'
      - '4108:4108'
      - '4109:4109'
    environment:
      - NODE_ENV=production
