import MuiThemeProvider from '../theme/MuiThemeProvider';
import './global.css';

export const metadata = {
  title: 'Welcome to survey-observations',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link
        href="https://fonts.googleapis.com/icon?family=Material+Icons"
        rel="stylesheet"
      />
      <head />
      <body>
        <MuiThemeProvider>{children}</MuiThemeProvider>
        {/* <ToastContainer /> */}
      </body>
    </html>
  );
}
