import { ToastContainer } from 'react-toastify';
import MuiThemeProvider from '../theme/MuiThemeProvider';
import './global.css';

export const metadata = {
  title: 'Welcome to survey-observations',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link
        href="https://fonts.googleapis.com/icon?family=Material+Icons"
        rel="stylesheet"
      />
      <head />
      <body>
        <MuiThemeProvider>{children}</MuiThemeProvider>
        <ToastContainer
          position="bottom-center"
          autoClose={2000} // ✅ must not be false here
          hideProgressBar
          closeButton={false}
          newestOnTop
        />
      </body>
    </html>
  );
}
