// app/layout.tsx
import './global.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import MuiThemeProvider from './app/theme/MuiThemeProvider';
import Head from 'next/head';

export const metadata = {
  title: 'Welcome to learner-web-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body>
        <MuiThemeProvider>{children}</MuiThemeProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
