// app/layout.tsx
import './global.css';
import MuiThemeProvider from './app/theme/MuiThemeProvider';

export const metadata = {
  title: 'Welcome to learner-web-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MuiThemeProvider>{children}</MuiThemeProvider>
      </body>
    </html>
  );
}
