const baseurl = process.env.NEXT_PUBLIC_MIDDLEWARE_URL;

const API_ENDPOINTS = {
  contentRead: (doId: string) => `${baseurl}/api/content/v1/read/${doId}?fields=artifactUrl`,
  academicYearsList: `${baseurl}/interface/v1/academicyears/list`,
  coursePlannerUpload: `${baseurl}/prathamservice/v1/course-planner/upload`,
  targetedSolutions: `${baseurl}/solutions/targetedSolutions?type=improvementProject&currentScopeOnly=true`,
  formRead: `${baseurl}/interface/v1/form/read`,
  accountCreate: `${baseurl}/interface/v1/account/create`,
  userUpdate: (userId: string | string[]) => `${baseurl}/interface/v1/user/update/${userId}`,
  myCohorts: (userId: string | string[]) => `${baseurl}/interface/v1/cohort/mycohorts/${userId}`,
  accountLogin: `${baseurl}/interface/v1/account/login`,
  authRefresh: `${baseurl}/interface/v1/account/auth/refresh`,
  authLogout: `${baseurl}/interface/v1/account/auth/logout`,
  userAuth: `${baseurl}/interface/v1/user/auth`,
  resetPassword: `${baseurl}/interface/v1/user/reset-password`,
  fieldOptionsRead: `${baseurl}/interface/v1/fields/options/read`,
  cohortSearch: `${baseurl}/interface/v1/cohort/search`,
  fieldOptionDelete: (type: string, option: string) => `${baseurl}/interface/v1/fields/options/delete/${type}?option=${option}`,
  fieldUpdate: (fieldId: string) => `${baseurl}/interface/v1/fields/update/${fieldId}`,
  cohortUpdate: (cohortId: string) => `${baseurl}/interface/v1/cohort/update/${cohortId}`,
  notificationSend: `${baseurl}/interface/v1/notification/send`,
  tenantRead: `${baseurl}/interface/v1/tenant/read`,
  tenantCreate: `${baseurl}/interface/v1/tenant/create`,
  tenantUpdate: (tenantId: string) => `${baseurl}/interface/v1/tenant/update/${tenantId}`,
  tenantDelete: (tenantId: string) => `${baseurl}/interface/v1/tenant/delete/${tenantId}`,
  tenantSearch: `${baseurl}/interface/v1/tenant/search`,
  userList: `${baseurl}/interface/v1/user/list`,
  cohortMemberList: `${baseurl}/interface/v1/cohortmember/list`,
  userRead: (userId: string | string[], fieldValue?: boolean) => 
  fieldValue !== undefined 
    ? `${baseurl}/interface/v1/user/read/${userId}?fieldvalue=${fieldValue}`
    : `${baseurl}/interface/v1/user/read/${userId}`,  suggestUsername: `${baseurl}/interface/v1/user/suggestUsername`,
  cohortUpdateUser: (userId: string | string[]) => `${baseurl}/interface/v1/cohort/update/${userId}`,
  formReadWithContext: (context: string, contextType: string) => `${baseurl}/interface/v1/form/read?context=${context}&contextType=${contextType}`,
  cohortCreate: `${baseurl}/interface/v1/cohort/create`,
  cohortMemberBulkCreate: `${baseurl}/interface/v1/cohortmember/bulkCreate`,
  cohortMemberUpdate: (membershipId: string | number) => `${baseurl}/interface/v1/cohortmember/update/${membershipId}`,
  notificationTemplate: `${baseurl}/notification-templates`,
  assessmentList: `${baseurl}/interface/v1/tracking/assessment/list`,
  assessmentSearchStatus: `${baseurl}/interface/v1/tracking/assessment/search/status`,
  assessmentSearch: `${baseurl}/interface/v1/tracking/assessment/search`,
  bulkAttendance: `${baseurl}/interface/v1/account/attendance/bulkAttendance`,
  attendanceCreate: `${baseurl}/interface/v1/attendance/create`,
  attendanceList: `${baseurl}/interface/v1/account/attendance/list`,
  cohortHierarchy: (cohortId: string) => `${baseurl}/interface/v1/cohort/cohortHierarchy/${cohortId}`,
  eventList: `${baseurl}/interface/v1/event/list`,
  eventCreate: `${baseurl}/interface/v1/event/create`,
  eventDetails: (eventRepetitionId: string) => `${baseurl}/interface/v1/event/${eventRepetitionId}`,
  deleteFieldValues: `${baseurl}/interface/v1/fields/values/delete`,
  forgotPassword: `${baseurl}/interface/v1/user/forgot-password`,
  passwordResetLink: `${baseurl}/interface/v1/user/password-reset-link`,
  userReadWithField: (userId: string | string[]) => `${baseurl}/interface/v1/user/read/${userId}?fieldvalue=false`,
  contentSearchStatus: `${baseurl}/v1/tracking/content/search/status`,
  contentCreate: `${baseurl}/interface/v1/tracking/content/create`,
  updateCohortUser: (userId: string | string[])=>`${baseurl}/user/v1/cohort/update/${userId}`
};

export default API_ENDPOINTS;
