const baseurl = process.env.NEXT_PUBLIC_MIDDLEWARE_URL;

const API_ENDPOINTS = {
  contentRead: (doId: string) => `${baseurl}/api/content/v1/read/${doId}?fields=artifactUrl`,
  academicYearsList: `${baseurl}/interface/v1/academicyears/list`,
  coursePlannerUpload: `${baseurl}/prathamservice/v1/course-planner/upload`,
  targetedSolutions: `${baseurl}/solutions/targetedSolutions?type=improvementProject&currentScopeOnly=true`,
  formRead: `${baseurl}/interface/v1/form/read`,
  accountCreate: `${baseurl}/interface/v1/account/create`,
  userUpdate: (userId: string) => `${baseurl}/interface/v1/user/update/${userId}`,
  myCohorts: (userId: string | string[]) => `${baseurl}/interface/v1/cohort/mycohorts/${userId}`,
  accountLogin: `${baseurl}/interface/v1/account/login`,
  authRefresh: `${baseurl}/interface/v1/account/auth/refresh`,
  authLogout: `${baseurl}/interface/v1/account/auth/logout`,
  userAuth: `${baseurl}/interface/v1/user/auth`,
  resetPassword: `${baseurl}/interface/v1/user/reset-password`,
  fieldOptionsRead: `${baseurl}/interface/v1/fields/options/read`,
  cohortSearch: `${baseurl}/interface/v1/cohort/search`,
  fieldOptionDelete: (type: string, option: string) => `${baseurl}/interface/v1/fields/options/delete/${type}?option=${option}`,
  fieldUpdate: (fieldId: string) => `${baseurl}/interface/v1/fields/update/${fieldId}`,
  cohortUpdate: (cohortId: string) => `${baseurl}/interface/v1/cohort/update/${cohortId}`,
  notificationSend: `${baseurl}/interface/v1/notification/send`,
  tenantRead: `${baseurl}/interface/v1/tenant/read`,
  tenantCreate: `${baseurl}/interface/v1/tenant/create`,
  tenantUpdate: (tenantId: string) => `${baseurl}/interface/v1/tenant/update/${tenantId}`,
  tenantDelete: (tenantId: string) => `${baseurl}/interface/v1/tenant/delete/${tenantId}`,
  tenantSearch: `${baseurl}/interface/v1/tenant/search`,
  userList: `${baseurl}/interface/v1/user/list`,
  cohortMemberList: `${baseurl}/interface/v1/cohortmember/list`,
  userRead: (userId: string | string[], fieldValue: boolean) => `${baseurl}/interface/v1/user/read/${userId}?fieldvalue=${fieldValue}`,
  suggestUsername: `${baseurl}/interface/v1/user/suggestUsername`,
  cohortUpdateUser: (userId?: string) => `${baseurl}/interface/v1/cohort/update/${userId}`,
  formReadWithContext: (context: string, contextType: string) => `${baseurl}/interface/v1/form/read?context=${context}&contextType=${contextType}`,
  cohortCreate: `${baseurl}/interface/v1/cohort/create`,
  cohortMemberBulkCreate: `${baseurl}/interface/v1/cohortmember/bulkCreate`,
  cohortMemberUpdate: (membershipId: string | number) => `${baseurl}/interface/v1/cohortmember/update/${membershipId}`,
  notificationTemplate: `${baseurl}/notification-templates`,
};

export default API_ENDPOINTS;
